-- ==========================================================================
-- Süreç Takip & Operasyon Paneli - Supabase SQL Şeması
-- ==========================================================================
-- Bu kodları Supabase panosundaki "SQL Editor" sekmesine yapıştırıp çalıştırarak
-- veritabanı tablolarınızı ve güvenlik politikalarını (RLS) saniyeler içinde oluşturabilirsiniz.

-- 1. GÖREVLER (TASKS) TABLOSU OLUŞTURMA
CREATE TABLE IF NOT EXISTS public.tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    title text NOT NULL,
    "desc" text,
    dept text NOT NULL,
    priority text NOT NULL,
    assignee text NOT NULL,
    "dueDate" date NOT NULL,
    status text NOT NULL,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid() NOT NULL
);

-- RLS (Satır Bazlı Güvenlik) Politikalarını Aktifleştir
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;

-- Görevler için Güvenlik Politikaları (Kullanıcılar sadece kendi verilerini okuyabilir ve yazabilir)
CREATE POLICY "Kullanıcılar sadece kendi süreç kartlarını görebilir" 
ON public.tasks FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Kullanıcılar sadece kendi süreç kartlarını ekleyebilir" 
ON public.tasks FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Kullanıcılar sadece kendi süreç kartlarını güncelleyebilir" 
ON public.tasks FOR UPDATE 
USING (auth.uid() = user_id);

CREATE POLICY "Kullanıcılar sadece kendi süreç kartlarını silebilir" 
ON public.tasks FOR DELETE 
USING (auth.uid() = user_id);


-- 2. HAREKET LOGLARI (ACTIVITIES) TABLOSU OLUŞTURMA
CREATE TABLE IF NOT EXISTS public.activities (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    text text NOT NULL,
    "taskTitle" text,
    "user" text NOT NULL,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid() NOT NULL
);

-- RLS (Satır Bazlı Güvenlik) Politikalarını Aktifleştir
ALTER TABLE public.activities ENABLE ROW LEVEL SECURITY;

-- Aktiviteler için Güvenlik Politikaları
CREATE POLICY "Kullanıcılar sadece kendi loglarını görebilir" 
ON public.activities FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Kullanıcılar sadece kendi loglarını ekleyebilir" 
ON public.activities FOR INSERT 
WITH CHECK (auth.uid() = user_id);
